definitions:
  account.AccountBalance:
    properties:
      balance:
        type: number
    type: object
  account.DepositInput:
    properties:
      amount:
        type: number
    type: object
  account.Withdraw:
    properties:
      amount:
        type: number
    type: object
  auth.Login:
    properties:
      cpf:
        type: string
      secret:
        type: string
    type: object
  entities.Account:
    properties:
      balance:
        type: number
      cpf:
        type: string
      createdAt:
        type: string
      id:
        type: string
      name:
        type: string
      secret:
        type: string
    type: object
  entities.AccountInput:
    properties:
      cpf:
        type: string
      name:
        type: string
      secret:
        type: string
    type: object
  entities.Transfer:
    properties:
      accountDestinationID:
        type: string
      accountOriginID:
        type: string
      amount:
        type: number
      createdAt:
        type: string
      id:
        type: string
    type: object
  entities.TransferInput:
    properties:
      accountDestinationID:
        type: string
      amount:
        type: number
    type: object
info:
  contact: {}
paths:
  /accounts:
    get:
      consumes:
      - application/json
      description: List all accounts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Account'
            type: array
        "400":
          description: Failed to decode
        "404":
          description: Accounts not found
        "500":
          description: Unexpected internal server error
      summary: Get accounts
    post:
      consumes:
      - application/json
      description: Create an account with the basic information
      parameters:
      - description: Body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/entities.AccountInput'
      produces:
      - application/json
      summary: Create an account
  /accounts/{id}/balance:
    get:
      consumes:
      - application/json
      description: show the balance of a specific account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.AccountBalance'
        "400":
          description: Failed to decode
        "404":
          description: Account not found
        "500":
          description: Unexpected internal server error
      summary: account balance
  /deposit:
    post:
      consumes:
      - application/json
      description: Make a deposit from an authentic account
      parameters:
      - description: Body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/account.DepositInput'
      produces:
      - application/json
      summary: Make a deposit
  /login:
    post:
      consumes:
      - application/json
      description: It takes a token to authenticate yourself to the application
      parameters:
      - description: Body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/auth.Login'
      produces:
      - application/json
      summary: Get a Auth
  /transfer:
    post:
      consumes:
      - application/json
      description: Transfer between accounts. The account that will make the transfer
        must be authenticated with a token.
      parameters:
      - description: Body
        in: body
        name: Body
        required: true
        schema:
          items:
            $ref: '#/definitions/entities.Transfer'
          type: array
      - description: Bearer Authorization Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      summary: Make a transfer
  /withdraw:
    post:
      consumes:
      - application/json
      description: Make a Withdraw from an authentic account
      parameters:
      - description: Body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/account.Withdraw'
      produces:
      - application/json
      summary: Make a Withdraw
swagger: "2.0"
